config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'
  resources :reservations
  resources :hairstyles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ActiveHash::Base
  self.data = [
    { id: 1, name: 'メニューを選んで下さい'},
    { id: 2, name: 'カット(1時間)'},
    { id: 3, name: 'カラー(2時間)'},
    { id: 4, name: 'ダブルカラー(2.5時間)'},
    { id: 5, name: '縮毛矯正(3時間)'}
  ]

  include ActiveHash::Associations
  has_many :reservations

end

app/models/reservation.rb
class Reservation < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :menu
  belongs_to :user

  validates :day, presence: true
  validates :time, presence: true
  validates :start_time, presence: true, uniqueness: true

  with_options numericality: { other_than: 1 } do
    validates :menu_id
  end

  validate :date_before_start
  validate :date_current_today
  validate :date_three_month_end

  def date_before_start
    errors.add(:day, "は過去の日付は選択できません。予約画面から正しい日付を選択してください。") if day < Date.current
  end

  def date_current_today
    errors.add(:day, "は当日は選択できません。予約画面から正しい日付を選択してください。") if day < (Date.current + 1)
  end

  def date_three_month_end
    errors.add(:day, "は3ヶ月以降の日付は選択できません。予約画面から正しい日付を選択してください。") if (Date.current >> 3) < day
  end

  def self.check_reservation_day(day)
    if day < Date.current
      return "過去の日付は選択できません。正しい日付を選択してください。"
    elsif day < (Date.current + 1)
      return "当日は選択できません。正しい日付を選択してください。"
    elsif (Date.current >> 3) < day
      return "3ヶ月以降の日付は選択できません。正しい日付を選択してください。"
    end
  end

  def self.reservations_after_three_month
    reservations = Reservation.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
    reservation_data = []
    reservations.each do |reservation|
      reservations_hash = {}
      reservations_hash.merge!(day: reservation.day.strftime("%Y-%m-%d"), time: reservation.time)
      reservation_data.push(reservations_hash)
    end
    reservation_data
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @reservations = Reservation.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
  end

  def new
    @reservation = Reservation.new
    @day = params[:day]
    @time = params[:time]
    @start_time = DateTime.parse(@day + " " + @time)
    message = Reservation.check_reservation_day(@day.to_date)
    if !!message
      redirect_to @reservation, flash: { alert: message }
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      
      redirect_to reservation_path @reservation.id
    else
      render :new
    end
  end

  private
  def reservation_params
    params.require(:reservation).permit(:day, :time, :user_id, :start_time, :menu_id, :order)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def times
    times = ["10:00",
             "11:00",
             "12:00",
             "13:00",
             "14:00",
             "15:00",
             "16:00",
             "17:00",
             "18:00",
             "19:00",
             "20:00"
            ]
  end

  def check_reservation(reservations, day, time)
    result = false
    reservations_count = reservations.count
    if reservations_count > 1
      reservations.each do |reservation|
        result = reservation[:day].eql?(day.strftime("%Y-%m-%d")) && reservation[:time].eql?(time)
        return result if result
      end
    elsif reservations_count == 1
      result = reservations[0][:day].eql?(day.strftime("%Y-%m-%d")) && reservations[0][:time].eql?(time)
      return result if result
    end
    return result
  end
  
end

app/views/hairstyles/new.html.erb
<%= form_with model: @hairstyle, url:hairstyles_path, local: true do |f| %>
  <div class="container">
    <h1>ヘアスタイル投稿</h1>
    <label>ヘアスタイル名 <span class="badge badge-danger">必須</span></label>
    <%= f.text_field :hairstylename, autofocus: true, class:"form-control", placeholder:"ヘアスタイル名" %>
    <label>ヘアスタイルについて <span class="badge badge-danger">必須</span></label>
    <%= f.text_area :detail, class:"form-control", placeholder:"ヘアスタイルについて" %>
    <label>性別 <span class="badge badge-danger">必須</span></label>
    <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"form-control"}) %>
    <label>髪の長さ <span class="badge badge-danger">必須</span></label>
    <%= f.collection_select(:hairlength_id, Hairlength.all, :id, :name, {}, {class:"form-control"}) %>
    <label>髪の色 <span class="badge badge-danger">必須</span></label>
    <%= f.collection_select(:haircolor_id, Haircolor.all, :id, :name, {}, {class:"form-control"}) %>
      <div class="field">
        <%= f.label :image, "ヘアスタイル写真" %> <span class="badge badge-danger">必須</span> <br>
        <%= f.file_field :image, id:"hairstyle_image" ,class:"form-control" %>
      </div>
    <br>
    <%= f.submit "投稿する" ,class:"btn btn-primary btn-block" %>
  </div>

<% end %>

app/views/homes/index.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=yes, maximum-scale=1.0, minimum-scale=1.0">
<title>美容室予約</title>
<meta name="keywords" content="">
<meta name="description" content="">

<link rel="stylesheet" href="assets/style.css" type="text/css" media="screen">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script>$(function(){$("div.panel").hide();$(".menu").click(function(){$(this).toggleClass("menuOpen").next().slideToggle();});})</script>
</head>

<body>
<header id="header">
  <!-- ロゴ -->
	<div class="logo">
		<a href="/"><img src="/assets/logo.png" width="45" height="45" alt="Sample site" /><p>Salon Reservation<span>Beauty makes life better</span></p></a>
	</div>
	<!-- / ロゴ -->
	<!-- 電話番号+受付時間 -->
	<div class="info">
		<p class="tel"><span>電話:</span> 0123-456-7890</p>
		<p class="open">受付時間: 全日 AM 10:00 〜 PM 8:00</p>
	</div>
	<!-- / 電話番号+受付時間 -->
</header>

<!-- メインナビゲーション -->
<nav id="mainNav">
	<div class="inner">
  	<a class="menu" id="menu"><span>MENU</span></a>
		<div class="panel">   
    	<ul>
				<% if user_signed_in? %>
					<li class="active"><a href= "/"><strong>トップページ</strong><span>Top</span></a></li>
					<li><a href="/reservations"><strong>美容室予約</strong><span>Reservation</span></a></li>
					<li><a href="/hairstyles"><strong>ヘアスタイル</strong><span>Hairstyle</span></a></li>
					<li><a href="#"><strong>マイページ</strong><span>Mypage</span></a></li>
					<li><a href="/users/edit"><strong>アカウント編集</strong><span>Account</span></a></li>
					<li class="last"><a href="/users/sign_out" data-method="delete"><strong>ログアウト</strong><span>Logout</span></a></li>
				<% else %>
					<li class="active"><a href= "/"><strong>トップページ</strong><span>Top</span></a></li>
					<li><a href="/hairstyles"><strong>ヘアスタイル</strong><span>Hairstyle</span></a></li>
					<li class="last"><a href="/users/sign_in"><strong>ログイン</strong><span>Login</span></a></li>
				<% end %>
			</ul>   
    </div>
	</div> 
</nav>
<!-- / メインナビゲーション -->
  
<div id="wrapper">
  
  <!-- メイン画像 -->
	<div id="mainBanner">
		<img src="/assets/美容室.jpg" width="930" alt="美容室店内写真">
	</div>
	<!-- / メイン画像 -->

  <!-- 3カラム -->
  <section class="gridWrapper">
		<article class="grid">
      <div class="box">
				<img src="/assets/top_m1.jpg" width="290" height="290" alt="トップ1">
				<h3>自然との調和を目指す企業です</h3>
				<p>ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。</p>
				<p class="readmore"><a href="subpage.html">詳細を確認する</a></p>
      </div>
		</article>
		<article class="grid">
			<div class="box">
      	<img src="/assets/top_m2.jpg" width="290" height="290" alt="トップ2">
				<h3>自然との調和を目指す企業です</h3>
				<p>ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。</p>
				<p class="readmore"><a href="subpage.html">詳細を確認する</a></p>
      </div>
		</article>
    <article class="grid">
    	<div class="box">
				<img src="/assets/top_m3.jpg" width="290" height="290" alt="トップ3">
				<h3>自然との調和を目指す企業です</h3>
				<p>ホームページサンプル株式会社では最新技術と自然との調和を目指します。革新的な技術で世の中を動かす企業を目指します。</p>
				<p class="readmore"><a href="subpage.html">詳細を確認する</a></p>
			</div>
    </article>
	</section>
	<!-- / 3カラム -->
  
</div>
 
<!-- フッター -->
<footer id="footer">
	<div class="inner">
  	<!-- 左側 -->
		<div id="info" class="grid">
			<!-- ロゴ -->
			<div class="logo">
				<a href="index.html"><img src="/assets/logo.png" width="45" height="45" alt="Sample site"><p>Company Name<br><span>Your Company Slogan</span></p></a>
			</div>
			<!-- / ロゴ -->
			<!-- 電話番号+受付時間 -->
			<div class="info">
				<p class="tel"><span>電話:</span> 012-3456-7890</p>
				<p class="open">受付時間: 平日 AM 10:00 〜 PM 5:00</p>
			</div>
			<!-- / 電話番号+受付時間 -->
		</div>  
		<!-- / 左側 -->
		<!-- 右側 ナビゲーション -->
		<ul class="footnav">
			<li><a href="subpage.html">eco・環境事業</a></li>
			<li><a href="subpage.html">コンピュータ事業</a></li>
			<li><a href="subpage.html">飲食店事業</a></li>
			<li><a href="subpage.html">介護・医療事業</a></li>
			<li><a href="subpage.html">ごあいさつ</a></li>
			<li><a href="subpage.html">サービス概要</a></li>
			<li><a href="subpage.html">会社情報</a></li>
			<li><a href="subpage.html">お問い合わせ</a></li>
			<li><a href="subpage.html">サイトマップ</a></li>
		</ul>
		<!-- / 右側 ナビゲーション -->
	</div>
</footer>
<!-- / フッター -->
<address>Copyright(c) 2013 Sample Inc. All Rights Reserved. Design by <a href="http://f-tpl.com" target="_blank" rel="nofollow">http://f-tpl.com</a></address>

</body>
</html>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand navbar-light">
    <%= link_to "トップページ", root_path, class: 'navbar-brand' %>
    <div id="Navber">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to '美容室予約', reservations_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'アカウント編集', edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'ヘアスタイル投稿', new_hairstyle_path, class: 'nav-link' %>
          <li class="nav-item active">
            <%= link_to 'ヘアスタイル一覧', hairstyles_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
      <% else %>
          <li class="nav-item active">
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>美容室予約</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reservations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h1>予約画面</h1>
      <p>3ヶ月先まで予約することができます。</p>
    </div>
    <div class="col-12 mt-3">
      <%= week_calendar events: @reservations do |date, reservations| %>
        <%= date.day %>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <h1>新規予約画面</h1>
    </div>
    <div class="col-12 mt-3 content">
      <%= form_with model: @reservation, local: true, class: 'form' do |form| %>
      <%= render 'layouts/error_messages', model: form.object %>
      <div class="day form-group">
        <%= form.label :day, '日付' %>
        <%= form.text_field :day, class: 'form-control', value: @day, readonly: true %>
      </div>
      <div class="time form-group">
        <%= form.label :time, '開始時間' %>
        <%= form.text_field :time, class: 'form-control', value: @time, readonly: true %>
      </div>

      <label>メニュー <span class="badge badge-danger">必須</span></label>
      <%= form.collection_select(:menu_id, Menu.all, :id, :name, {}, {class:"form-control"}) %>

      <label>希望ヘアスタイルのオーダー <span class="badge badge-success">任意</span></label>
      <%= form.text_field :order, autofocus: true, class:"form-control", placeholder:"希望ヘアスタイルのオーダー" %>



      <br>

      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :start_time, value: @start_time %>
      <div class="submit">
        <%= form.submit value: '予約する', class: 'btn btn-primary btn-block' %>
      </div>
    <% end %>

 
    <div class="col-12 text-right">
      <%= link_to '戻る', reservations_path %>
    </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <h1>予約詳細画面</h1>
    </div>
    <div class="col-12 mt-3 text-center content">
      <div>
        <label><strong>日付：</strong></label>
        <p style="display:inline;"><%= @reservation.day %></p>
      </div>
      <div>
        <label><strong>時間：</strong></label>
        <p style="display:inline;"><%= @reservation.time %></p>
      </div>
      <div>
        <label><strong>メニュー：</strong></label>
        <p style="display:inline;"><%= @reservation.menu.name %></p>
      </div>
     <div class="col-12 text-right">
      <%= link_to '予約画面に戻る', reservations_path %>
    </div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    <% reservations = Reservation.reservations_after_three_month %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>時間</th>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <td></td>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
         <% times.each do |time| %>
          <tr>
            <td><%= time %></td>
            <% week.each do |day| %>
              <td>
              <% if check_reservation(reservations, day, time) %>
                  <%= '×' %>
                <% else %>
               <%= link_to new_reservation_path(day: day, time: time) do %>
                    <%= '○' %>
                  <% end %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>